export const messages = [
  {
    id:1,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Anna Dalonzo',
    mess: 'rebuild finished, watching for changes.',
    date: '12:45',
    category: 'work',
    online: true,
  },
  {
    id:2,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Anna Dalonzo',
    mess: 'generate lazy started',
    date: '12:45',
    category: 'family',
    online: true,
  },
  {
    id:3,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Anna Dalonzo',
    mess: 'generate lazy finished in 141 ms',
    date: '10:45',
    category: 'friends',
    online: false,
  },
  {
    id:4,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Anna Dalonzo',
    mess: 'Hello everyone!!!',
    date: '10:45',
    category: 'friends',
    online: true,
  },
  {
    id:5,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Anna Dalonzo',
    mess: 'transpile started',
    date: '10:45',
    category: 'work',
    online: false,
  },
  {
    id:6,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Anna Dalonzo',
    mess: 'Hello everyone!!!',
    date: '10:45',
    category: 'work',
    online: true,
  },
  {
    id:7,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Anna Dalonzo',
    mess: 'Hello everyone!!!',
    date: '10:45',
    category: 'work',
    online: false,
  },
  {
    id:8,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Saqhan Dalonzo',
    mess: 'Hello everyone!!!',
    date: '20:00',
    category: 'family',
    online: true,
  },
  {
    id:9,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Saqhan Chrome',
    mess: 'Hello everyone!!! category',
    date: '15:4',
    category: 'friends',
    online: false,
  },
  {
    id:10,
    img: 'https://via.placeholder.com/300x300?text=User',
    name: 'Saqhan Chrome',
    mess: 'Generate lazy started',
    date: '15:4',
    category: 'friends',
    online: false,
  },

];

export const categories = [
  {
    name: 'All',
    id: 'all',
  },
  {
    name: 'Work',
    id: 'work',
  },
  {
    name: 'Family',
    id: 'family',
  },
  {
    name: 'Friends',
    id: 'friends',
  },
]
